"use client";
import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";

// export const metadata = {
//   title: "ZAG ERP",
//   description: "Generated by create next app",
// };

interface RootLayoutInterface {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutInterface) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
